### ISSUE TITLE
SC-100 violation!

### ISSUE THREAD

**Issue by jgmuchiri** [BloomTech-Labs/story-squad-fe-archived#37]
https://github.com/Lambda-School-Labs/story-squad-fe/blob/604c04da384cdf1f52246e496d2ece2dd90c8ab6/src/app/components/dashboard/stripe/wrapper/wrapper.component.tsx#L8

**RE:** https://lambda-school-labs.github.io/labs-engineering-standards/topics/security/#sc-100-never-commit-secrets

**Comment by lgv-0** [comment]
After digging through the [API docs](https://stripe.com/docs/keys), it looks like keys beginning with **pk** are public (publishable) keys - not secret, @ryan-hamblin are we okay to close this?
