### ISSUE TITLE
Forbidden non-null assertion

### ISSUE THREAD

**Issue by itshui3** [BloomTech-Labs/story-squad-fe-archived#51]
./src/app/components/child-dashboard/team-join/team-join.component.tsx
Loc 268:13 : Forbidden non-null assertion @typescript-eslint/no-non-null-assertion

./src/app/components/child-dashboard/child-home/child-home.component.tsx
Loc 282:13 : Forbidden non-null assertion @typescript-eslint/no-non-null-assertion

./src/app/components/child-dashboard/kid-progress/kid-progress.component.tsx
Loc 297:13 : Forbidden non-null assertion @typescript-eslint/no-non-null-assertion

Doesn't break the app FE, but needs fixing for good practice

**Comment by squashgray** [comment]
fixed
