### ISSUE TITLE
Multiple Page Submissions on Match Up Page

### ISSUE THREAD

**Issue by B-Griffinn** [BloomTech-Labs/story-squad-fe-archived#83]
- what if a child submits multiple pages?
It would be ideal to only show page1 in the modal on the match up page and when a user clicks on the modal you can carousel / see all pages submitted. 
- The modals on the match up page may need to accept an array that allows us to map through the entire list of submissions and display accordingly in the modal.

**Comment by jTCode2408** [comment]
-Fixed. Modals now have conditional rendering based on page # of stories.
